# Generated by Django 2.1.3 on 2018-11-16 14:37

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=70)),
                ('picture_preview', imagekit.models.fields.ProcessedImageField(upload_to='media')),
                ('slug', models.SlugField(max_length=70, unique=True)),
                ('disc', models.CharField(max_length=70)),
                ('body', models.TextField(blank=True, db_index=True)),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_pub'],
            },
        ),
    ]
