# Generated by Django 2.1.3 on 2018-11-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktools', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='posts', to='worktools.Tag'),
        ),
    ]
