# Generated by Django 2.1.3 on 2018-11-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktools', '0003_tool_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=111111111, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
