# Generated by Django 2.1.3 on 2018-11-22 11:03

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('worktools', '0004_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='slide_four',
            field=imagekit.models.fields.ProcessedImageField(default=11111111111111111111111, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='slide_one',
            field=imagekit.models.fields.ProcessedImageField(default=11111111111111111, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='slide_three',
            field=imagekit.models.fields.ProcessedImageField(default=11111111111111111111, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='slide_two',
            field=imagekit.models.fields.ProcessedImageField(default=11111111111111111111111111111, upload_to='media'),
            preserve_default=False,
        ),
    ]
